modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mixins]]
config="yamidelight.mixins.json"

[[mixins]]
config="yamidelight-common.mixins.json"

[[mixins]]
config="yamidelight.feast.mixins.json"

[[mods]]
modId="yamidelight"
version="1.0.0"
displayName="Yami Delight"
authors="SAI"
description='''Winefox preparation, feasts, and collectible winefox heads, with Touhou Little Maid and Farmer's Delight integration.'''

[[dependencies.yamidelight]]
modId="farmersdelight"
type="required"
versionRange="[1.3.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.yamidelight]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.yamidelight]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.yamidelight]]
modId="touhou_little_maid"
type="required"
versionRange="[1.5.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.yamidelight]]
modId="yes_steve_model"
type="optional"
versionRange="[2.3.3,)"
ordering="AFTER"
side="BOTH"
